import { Commons } from "../src/commons";

export function deepCopy (o : Object) {
  return JSON.parse(JSON.stringify( o ));
}

export function compareKeys(objectA : any, objectB : any) : boolean {
  var aKeys = Object.keys(objectA).sort();
  var bKeys = Object.keys(objectB).sort();
  return JSON.stringify(aKeys) === JSON.stringify(bKeys);
}

export let restaurants : Commons.Restaurant[] = [
  new Commons.RestaurantBuilder()
      .setRestaurantId(13048)
      .setRestaurantName("גוטה בריא ומהיר")
      .setRestaurantAddress("תובל 19 רמת גן")
      .setRestaurantCityName("רמת גן")
      .setRestaurantLogoUrl("https://d25t2285lxl5rf.cloudfront.net/images/shops/13048.gif")
      .setRestaurantPhone("03-5440053")
      .setRestaurantCuisineList("אוכל ביתי) בשרים) סלטים/סנדוויצ`ים")
      .setNumOfReviews(3490)
      .setReviewsRank(8)
      .setDistanceFromUser("874.89 מטרים")
      .setDistanceFromUserInMeters(874.8921943511485)
      .setIsOpenForDelivery(true)
      .setIsOpenForPickup(false)
      .setMinimumOrder("₪140.00")
      .setMinimumPriceForOrder(140)
      .setDeliveryPrice("חינם")
      .setDeliveryPriceForOrder(0)
      .setIsKosher("כשר")
      .setRestaurantKosher("המסעדה כשרה")
      .setDeliveryRemarks("חלוקת משלוחים החל מ 11:30")
      .setResGeoLocation_lon(34.8021509)
      .setResGeoLocation_lat(32.0848375)
      .setHappyHourDiscount("")
      .setHappyHourDiscountPercent(0)
      .setDeliveryChargeValueType(0)
      .setHappyHourDiscountValidityString("תקף עד 00:00")
      .setStartOrderURL(null)
      .setActivityHours("08:00 - 16:00")
      .setPickupActivityHours("00:00 - 00:00")
      .setDeliveryTime("עד 75 דק'")
      .setArrivalDeliveryTime("11:32 - 11:17")
      .setEstimatedDeliveryTime("עד 75 דק'")
      .setArrivalEstimatedDeliveryTime("11:32 - 11:17")
      .setShowEstimatedDeliveryTimes(true)
      .setIsHappyHourActive(false)
      .setIsPromotionActive(false)
      .setCompanyFlag(false)
      .setIsOverPoolMin(false)
      .setPoolSum("₪ 0.00")
      .setPoolSumNumber(0)
      .setDeliveryEndTime("16:00")
      .setIsTerminalActive(true)
      .setIsActiveForDelivery(true)
      .setIsActiveForPickup(true)
      .setBookmarked(false)
      .setNumberOfBookmarked(489)
      .setDiscountCouponPercent(0)
      .setCouponHasRestrictions(false)
      .setHasLogo(true)
      .setResWebsiteMode(1)
      .setPriority(6)
      .setKosherCertificateImgUrl("")
      .setIsExpressRes(false)
      .setShowSEOTagsForRes(false)
      .setHappyHourResRulesDescription([])
      .setPhoneOrdersOnlyOnPortals(false)
      .setDeliveryStartTime("08:00")
      .setPickupStartTime("00:00")
      .setPickupEndTime("00:00")
      .build(),
  new Commons.RestaurantBuilder()
      .setRestaurantId(1238)
      .setRestaurantName("דיקסי")
      .setRestaurantAddress("תובל 19 רמת גן")
      .setRestaurantCityName("רמת גן")
      .setRestaurantLogoUrl("https://d25t2285lxl5rf.cloudfront.net/images/shops/13048.gif")
      .setRestaurantPhone("03-5440053")
      .setRestaurantCuisineList("אוכל ביתי) בשרים) סלטים/סנדוויצ`ים")
      .setNumOfReviews(531)
      .setReviewsRank(8)
      .setDistanceFromUser("874.89 מטרים")
      .setDistanceFromUserInMeters(500)
      .setIsOpenForDelivery(true)
      .setIsOpenForPickup(false)
      .setMinimumOrder("₪140.00")
      .setMinimumPriceForOrder(140)
      .setDeliveryPrice("חינם")
      .setDeliveryPriceForOrder(0)
      .setIsKosher("כשר")
      .setRestaurantKosher("המסעדה כשרה")
      .setDeliveryRemarks("חלוקת משלוחים החל מ 11:30")
      .setResGeoLocation_lon(34.8021509)
      .setResGeoLocation_lat(32.0848375)
      .setHappyHourDiscount("")
      .setHappyHourDiscountPercent(0)
      .setDeliveryChargeValueType(0)
      .setHappyHourDiscountValidityString("תקף עד 00:00")
      .setStartOrderURL(null)
      .setActivityHours("08:00 - 16:00")
      .setPickupActivityHours("00:00 - 00:00")
      .setDeliveryTime("עד 75 דק'")
      .setArrivalDeliveryTime("11:32 - 11:17")
      .setEstimatedDeliveryTime("עד 75 דק'")
      .setArrivalEstimatedDeliveryTime("11:32 - 11:17")
      .setShowEstimatedDeliveryTimes(true)
      .setIsHappyHourActive(false)
      .setIsPromotionActive(false)
      .setCompanyFlag(false)
      .setIsOverPoolMin(true)
      .setPoolSum("₪ 95.00")
      .setPoolSumNumber(95)
      .setDeliveryEndTime("16:00")
      .setIsTerminalActive(true)
      .setIsActiveForDelivery(true)
      .setIsActiveForPickup(true)
      .setBookmarked(false)
      .setNumberOfBookmarked(489)
      .setDiscountCouponPercent(0)
      .setCouponHasRestrictions(false)
      .setHasLogo(true)
      .setResWebsiteMode(1)
      .setPriority(6)
      .setKosherCertificateImgUrl("")
      .setIsExpressRes(false)
      .setShowSEOTagsForRes(false)
      .setHappyHourResRulesDescription([])
      .setPhoneOrdersOnlyOnPortals(false)
      .setDeliveryStartTime("08:00")
      .setPickupStartTime("00:00")
      .setPickupEndTime("00:00")
      .build(),
  new Commons.RestaurantBuilder()
      .setRestaurantId(123456)
      .setRestaurantName("השדרה")
      .setRestaurantAddress("תובל 19 רמת גן")
      .setRestaurantCityName("רמת גן")
      .setRestaurantLogoUrl("https://d25t2285lxl5rf.cloudfront.net/images/shops/13048.gif")
      .setRestaurantPhone("03-5440053")
      .setRestaurantCuisineList("אוכל ביתי) בשרים) סלטים/סנדוויצ`ים")
      .setNumOfReviews(531)
      .setReviewsRank(8)
      .setDistanceFromUser("874.89 מטרים")
      .setDistanceFromUserInMeters(1500)
      .setIsOpenForDelivery(true)
      .setIsOpenForPickup(false)
      .setMinimumOrder("₪140.00")
      .setMinimumPriceForOrder(140)
      .setDeliveryPrice("חינם")
      .setDeliveryPriceForOrder(0)
      .setIsKosher("כשר")
      .setRestaurantKosher("המסעדה כשרה")
      .setDeliveryRemarks("חלוקת משלוחים החל מ 11:30")
      .setResGeoLocation_lon(34.8021509)
      .setResGeoLocation_lat(32.0848375)
      .setHappyHourDiscount("")
      .setHappyHourDiscountPercent(0)
      .setDeliveryChargeValueType(0)
      .setHappyHourDiscountValidityString("תקף עד 00:00")
      .setStartOrderURL(null)
      .setActivityHours("08:00 - 16:00")
      .setPickupActivityHours("00:00 - 00:00")
      .setDeliveryTime("עד 75 דק'")
      .setArrivalDeliveryTime("11:32 - 11:17")
      .setEstimatedDeliveryTime("עד 75 דק'")
      .setArrivalEstimatedDeliveryTime("11:32 - 11:17")
      .setShowEstimatedDeliveryTimes(true)
      .setIsHappyHourActive(false)
      .setIsPromotionActive(false)
      .setCompanyFlag(false)
      .setIsOverPoolMin(true)
      .setPoolSum("₪ 95.00")
      .setPoolSumNumber(95)
      .setDeliveryEndTime("16:00")
      .setIsTerminalActive(true)
      .setIsActiveForDelivery(true)
      .setIsActiveForPickup(true)
      .setBookmarked(false)
      .setNumberOfBookmarked(489)
      .setDiscountCouponPercent(0)
      .setCouponHasRestrictions(false)
      .setHasLogo(true)
      .setResWebsiteMode(1)
      .setPriority(6)
      .setKosherCertificateImgUrl("")
      .setIsExpressRes(false)
      .setShowSEOTagsForRes(false)
      .setHappyHourResRulesDescription([])
      .setPhoneOrdersOnlyOnPortals(false)
      .setDeliveryStartTime("08:00")
      .setPickupStartTime("00:00")
      .setPickupEndTime("00:00")
      .build()
];