module.exports = {
    compareKeys: function(objectA : Object, objectB : Object) {
        var aKeys = Object.keys(objectA).sort();
        var bKeys = Object.keys(objectB).sort();
        return JSON.stringify(aKeys) === JSON.stringify(bKeys);
      },
    restaurants: [{
        "RestaurantId": 13048,
        "RestaurantName": "גוטה בריא ומהיר",
        "RestaurantAddress": "תובל 19 רמת גן",
        "RestaurantCityName": "רמת גן",
        "RestaurantLogoUrl": "https://d25t2285lxl5rf.cloudfront.net/images/shops/13048.gif",
        "RestaurantPhone": "03-5440053",
        "RestaurantCuisineList": "אוכל ביתי, בשרים, סלטים/סנדוויצ`ים",
        "NumOfReviews": 3490,
        "ReviewsRank": 8,
        "distanceFromUser": "874.89 מטרים",
        "distanceFromUserInMeters": 874.8921943511485,
        "IsOpenForDelivery": true,
        "IsOpenForPickup": false,
        "MinimumOrder": "₪140.00",
        "MinimumPriceForOrder": 140,
        "DeliveryPrice": "חינם",
        "DeliveryPriceForOrder": 0,
        "IsKosher": "כשר",
        "RestaurantKosher": "המסעדה כשרה",
        "DeliveryRemarks": "חלוקת משלוחים החל מ 11:30",
        "ResGeoLocation_lon": 34.8021509,
        "ResGeoLocation_lat": 32.0848375,
        "HappyHourDiscount": "",
        "HappyHourDiscountPercent": 0,
        "deliveryChargeValueType": 0,
        "HappyHourDiscountValidityString": "תקף עד 00:00",
        "StartOrderURL": null,
        "ActivityHours": "08:00 - 16:00",
        "PickupActivityHours": "00:00 - 00:00",
        "DeliveryTime": "עד 75 דק'",
        "ArrivalDeliveryTime": "11:32 - 11:17",
        "EstimatedDeliveryTime": "עד 75 דק'",
        "ArrivalEstimatedDeliveryTime": "11:32 - 11:17",
        "ShowEstimatedDeliveryTimes": true,
        "IsHappyHourActive": false,
        "IsPromotionActive": false,
        "CompanyFlag": false,
        "IsOverPoolMin": false,
        "PoolSum": "₪ 0.00",
        "PoolSumNumber": 0,
        "DeliveryEndTime": "16:00",
        "IsTerminalActive": true,
        "IsActiveForDelivery": true,
        "IsActiveForPickup": true,
        "Bookmarked": false,
        "NumberOfBookmarked": 489,
        "DiscountCouponPercent": 0,
        "CouponHasRestrictions": false,
        "HasLogo": true,
        "ResWebsiteMode": 1,
        "Priority": 6,
        "KosherCertificateImgUrl": "",
        "IsExpressRes": false,
        "ShowSEOTagsForRes": false,
        "HappyHourResRulesDescription": [],
        "PhoneOrdersOnlyOnPortals": false,
        "DeliveryStartTime": "08:00",
        "PickupStartTime": "00:00",
        "PickupEndTime": "00:00"
    }, {
        "RestaurantId": 1238,
        "RestaurantName": "דיקסי",
        "RestaurantAddress": "תובל 19 רמת גן",
        "RestaurantCityName": "רמת גן",
        "RestaurantLogoUrl": "https://d25t2285lxl5rf.cloudfront.net/images/shops/13048.gif",
        "RestaurantPhone": "03-5440053",
        "RestaurantCuisineList": "אוכל ביתי, בשרים, סלטים/סנדוויצ`ים",
        "NumOfReviews": 531,
        "ReviewsRank": 8,
        "distanceFromUser": "874.89 מטרים",
        "distanceFromUserInMeters": 500,
        "IsOpenForDelivery": true,
        "IsOpenForPickup": false,
        "MinimumOrder": "₪140.00",
        "MinimumPriceForOrder": 140,
        "DeliveryPrice": "חינם",
        "DeliveryPriceForOrder": 0,
        "IsKosher": "כשר",
        "RestaurantKosher": "המסעדה כשרה",
        "DeliveryRemarks": "חלוקת משלוחים החל מ 11:30",
        "ResGeoLocation_lon": 34.8021509,
        "ResGeoLocation_lat": 32.0848375,
        "HappyHourDiscount": "",
        "HappyHourDiscountPercent": 0,
        "deliveryChargeValueType": 0,
        "HappyHourDiscountValidityString": "תקף עד 00:00",
        "StartOrderURL": null,
        "ActivityHours": "08:00 - 16:00",
        "PickupActivityHours": "00:00 - 00:00",
        "DeliveryTime": "עד 75 דק'",
        "ArrivalDeliveryTime": "11:32 - 11:17",
        "EstimatedDeliveryTime": "עד 75 דק'",
        "ArrivalEstimatedDeliveryTime": "11:32 - 11:17",
        "ShowEstimatedDeliveryTimes": true,
        "IsHappyHourActive": false,
        "IsPromotionActive": false,
        "CompanyFlag": false,
        "IsOverPoolMin": true,
        "PoolSum": "₪ 95.00",
        "PoolSumNumber": 95,
        "DeliveryEndTime": "16:00",
        "IsTerminalActive": true,
        "IsActiveForDelivery": true,
        "IsActiveForPickup": true,
        "Bookmarked": false,
        "NumberOfBookmarked": 489,
        "DiscountCouponPercent": 0,
        "CouponHasRestrictions": false,
        "HasLogo": true,
        "ResWebsiteMode": 1,
        "Priority": 6,
        "KosherCertificateImgUrl": "",
        "IsExpressRes": false,
        "ShowSEOTagsForRes": false,
        "HappyHourResRulesDescription": [],
        "PhoneOrdersOnlyOnPortals": false,
        "DeliveryStartTime": "08:00",
        "PickupStartTime": "00:00",
        "PickupEndTime": "00:00"
    }]
};